<?php

/**
 * Add support for extra wiki tags
 */

/**
 * SyntaxHighlight_GeSHi
 */
wfLoadExtension( 'SyntaxHighlight_GeSHi' );

/**
 * Math
 */
wfLoadExtension( 'Math' );
$wgDefaultUserOptions['math']                 = 'mathml';
# $wgMathFullRestbaseURL                      = 'https://api.formulasearchengine.com/';
$wgMathFullRestbaseURL                        = 'https://en.wikipedia.org/api/rest_';

/**
 * Poem
 * Add support for the <poem> tag
 * https://www.mediawiki.org/wiki/Extension:Poem
 */
wfLoadExtension( 'Poem' );

/**
 * Linter
 * Review wiki errors generated by Parsoid (don't work)
 * https://www.mediawiki.org/wiki/Extension:Linter
 */
wfLoadExtension( 'Linter' );
