<?php
# This file was automatically generated by the MediaWiki 1.27.0-wmf.9
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
    exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath                                 = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer                                     = getenv( 'MEDIAWIKI_SERVER' ) ;
$wgArticlePath                                = '/wiki/$1';
$wgScriptPath                                 = '/w';

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath                           = $wgScriptPath;

## Database settings
$wgDBtype                                     = "mysql";
$wgDBserver                                   = getenv ( 'MYSQL_DB_URL'   );
$wgDBname                                     = getenv ( 'MYSQL_DB_NAME'  );
$wgDBuser                                     = getenv ( 'MYSQL_USER'     );
$wgDBpassword                                 = getenv ( 'MYSQL_PASSWORD' );

# MySQL specific settings
$wgDBprefix                                   = "mw_";

# MySQL table options to use during installation or update
$wgDBTableOptions                             = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5                                   = true;

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode                               = "sv";

$wgSecretKey                                  = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey                                 = "xxxxxxxxxxxxxxxxx";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3                                      = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin                                = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkins( array( 'Timeless', 'Vector' ) );

$wgShowExceptionDetails                       = true;

# Load all *.php files in the settings.d directory
foreach (glob($IP."/settings.d/*.php") as $filename)
{
    include $filename;
}
